server:
  port: 8000
spring:
  application:
    name: mock
  datasource:
    password: sofi
    url: jdbc:h2:mem:testdb?createDatabaseIfNotExist=true
    username: sofi
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true